// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA6brcOzGVTbA0l6uOAZjPrDreg0U2nK8',
    appId: '1:565579504568:web:08a8d8f7985c817d100d4d',
    messagingSenderId: '565579504568',
    projectId: 'creationedge-3b4fe',
    authDomain: 'creationedge-3b4fe.firebaseapp.com',
    storageBucket: 'creationedge-3b4fe.firebasestorage.app',
    measurementId: 'G-4GL7S8QSVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJc7rcClKlJD0dwE8oJJFcVtZnJrdKOJQ',
    appId: '1:565579504568:android:a4206eec03135f25100d4d',
    messagingSenderId: '565579504568',
    projectId: 'creationedge-3b4fe',
    storageBucket: 'creationedge-3b4fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDStNhL8-2GVMVhPCrJDoCc8IURnMMrY3g',
    appId: '1:565579504568:ios:1e185c7ffb7413a6100d4d',
    messagingSenderId: '565579504568',
    projectId: 'creationedge-3b4fe',
    storageBucket: 'creationedge-3b4fe.firebasestorage.app',
    iosBundleId: 'com.creationedge.app.creationEdge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDStNhL8-2GVMVhPCrJDoCc8IURnMMrY3g',
    appId: '1:565579504568:ios:1e185c7ffb7413a6100d4d',
    messagingSenderId: '565579504568',
    projectId: 'creationedge-3b4fe',
    storageBucket: 'creationedge-3b4fe.firebasestorage.app',
    iosBundleId: 'com.creationedge.app.creationEdge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA6brcOzGVTbA0l6uOAZjPrDreg0U2nK8',
    appId: '1:565579504568:web:945b449f8194f153100d4d',
    messagingSenderId: '565579504568',
    projectId: 'creationedge-3b4fe',
    authDomain: 'creationedge-3b4fe.firebaseapp.com',
    storageBucket: 'creationedge-3b4fe.firebasestorage.app',
    measurementId: 'G-0NYNJ0NSL9',
  );
}
